### PR TITLE
use cache.clear() to flush django's cache

### PR DESCRIPTION
**Pull request by sunweaver**
This allows using memcached as caching backend (and probably others).

The cache.clear() method is has been the official API for cache flushing now for a while in Django (the implementation occured 6yrs ago or so [1]).

However, this patch will logoff the user when clearing the cache.

Btw.: I use memcached on Debian jessie, because the django redis cache backend is not packaged for jessie (anymore -> on Debian wheezy, redis could be used as caching backend in django 1.4).

[1] https://code.djangoproject.com/ticket/11503

### CODE REVIEW

**Comment by sunweaver** [comment]
Ooops... you obviously did a force-push on the jessie branch recently. This PR doest not apply cleanly anymore.

Please checkout commit hash #1119e4d and review the patch provided there.

**Comment by dblia** [comment]
Hello Mike,

This is actually a WIP branch, so you'll probably see a lot of force-pushes.
I'll look at your suggestions though and I'll reply to you soon.

**Comment by sunweaver** [comment]
Could you then enable the issue tracker for this repo/branch? So, I can send my patches via the issue tracker. (Next patch I propose is for enabling/disabling Java VNC (we want to use websock VNC only here).

**Comment by dblia** [comment]
Same as (https://github.com/skroutz/ganetimgr/pull/3).

**Pull request closed without merging**
